plugins:
  - rubocop-rake

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  NewCops: enable

  Exclude:
    - "bin/*"
    - "README.md"
    - "spec/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Exclude:
    - "lib/gem_changelog_diff/cli.rb"
    - "lib/gem_changelog_diff/github_client.rb"
